### ISSUE TITLE
docker-compose Stuck on Geographic Selection

### ISSUE THREAD

**Issue by lbhopper** [NuttCorp/uvdesk#2]
When docker-compose up -d is called on a new installation and starts running, the script hangs at a geolocation selection which cannot be made.

<img width="785" alt="image" src="https://github.com/NuttCorp/uvdesk/assets/116280844/d04b1cf2-6ac8-41ea-90b8-b95eb0391e48">

What app/service is causing this to occur?

**Comment by Dragonius** [comment]
it NEEDS "environment" on docker-compose.yaml
    environment:
      - TZ=Europe/Helsinki

**Comment by lbhopper** [comment]
thank you I'll make the change
